export const exerciseMuscleSeeds = [
  {
    exerciseCode: "bench_press_barbell",
    muscleCode: "chest",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "bench_press_barbell",
    muscleCode: "triceps",
    contributionWeight: 0.5,
    isPrimary: false,
  },
  {
    exerciseCode: "bench_press_barbell",
    muscleCode: "front_delts",
    contributionWeight: 0.3,
    isPrimary: false,
  },
  {
    exerciseCode: "incline_bench_press_barbell",
    muscleCode: "upper_chest",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "incline_bench_press_barbell",
    muscleCode: "triceps",
    contributionWeight: 0.5,
    isPrimary: false,
  },
  {
    exerciseCode: "incline_bench_press_barbell",
    muscleCode: "front_delts",
    contributionWeight: 0.4,
    isPrimary: false,
  },
  {
    exerciseCode: "bench_press_dumbbell",
    muscleCode: "chest",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "bench_press_dumbbell",
    muscleCode: "triceps",
    contributionWeight: 0.45,
    isPrimary: false,
  },
  {
    exerciseCode: "bench_press_dumbbell",
    muscleCode: "front_delts",
    contributionWeight: 0.3,
    isPrimary: false,
  },
  {
    exerciseCode: "incline_bench_press_dumbbell",
    muscleCode: "upper_chest",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "incline_bench_press_dumbbell",
    muscleCode: "triceps",
    contributionWeight: 0.45,
    isPrimary: false,
  },
  {
    exerciseCode: "incline_bench_press_dumbbell",
    muscleCode: "front_delts",
    contributionWeight: 0.4,
    isPrimary: false,
  },
  {
    exerciseCode: "chest_fly_machine",
    muscleCode: "chest",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "chest_fly_machine",
    muscleCode: "front_delts",
    contributionWeight: 0.2,
    isPrimary: false,
  },
  {
    exerciseCode: "shoulder_press_barbell",
    muscleCode: "front_delts",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "shoulder_press_barbell",
    muscleCode: "triceps",
    contributionWeight: 0.55,
    isPrimary: false,
  },
  {
    exerciseCode: "shoulder_press_barbell",
    muscleCode: "side_delts",
    contributionWeight: 0.35,
    isPrimary: false,
  },
  {
    exerciseCode: "shoulder_press_dumbbell",
    muscleCode: "front_delts",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "shoulder_press_dumbbell",
    muscleCode: "triceps",
    contributionWeight: 0.5,
    isPrimary: false,
  },
  {
    exerciseCode: "shoulder_press_dumbbell",
    muscleCode: "side_delts",
    contributionWeight: 0.4,
    isPrimary: false,
  },
  {
    exerciseCode: "lateral_raise_dumbbell",
    muscleCode: "side_delts",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "rear_delt_fly_machine",
    muscleCode: "rear_delts",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "rear_delt_fly_machine",
    muscleCode: "upper_back",
    contributionWeight: 0.3,
    isPrimary: false,
  },
  {
    exerciseCode: "pull_up_bodyweight",
    muscleCode: "lats",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "pull_up_bodyweight",
    muscleCode: "biceps",
    contributionWeight: 0.45,
    isPrimary: false,
  },
  {
    exerciseCode: "pull_up_bodyweight",
    muscleCode: "upper_back",
    contributionWeight: 0.35,
    isPrimary: false,
  },
  {
    exerciseCode: "lat_pulldown_cable",
    muscleCode: "lats",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "lat_pulldown_cable",
    muscleCode: "biceps",
    contributionWeight: 0.45,
    isPrimary: false,
  },
  {
    exerciseCode: "lat_pulldown_cable",
    muscleCode: "upper_back",
    contributionWeight: 0.3,
    isPrimary: false,
  },
  {
    exerciseCode: "barbell_row",
    muscleCode: "upper_back",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "barbell_row",
    muscleCode: "lats",
    contributionWeight: 0.7,
    isPrimary: false,
  },
  {
    exerciseCode: "barbell_row",
    muscleCode: "rear_delts",
    contributionWeight: 0.35,
    isPrimary: false,
  },
  {
    exerciseCode: "seated_cable_row",
    muscleCode: "upper_back",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "seated_cable_row",
    muscleCode: "lats",
    contributionWeight: 0.65,
    isPrimary: false,
  },
  {
    exerciseCode: "seated_cable_row",
    muscleCode: "biceps",
    contributionWeight: 0.35,
    isPrimary: false,
  },
  {
    exerciseCode: "face_pull_cable",
    muscleCode: "rear_delts",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "face_pull_cable",
    muscleCode: "upper_back",
    contributionWeight: 0.45,
    isPrimary: false,
  },
  {
    exerciseCode: "barbell_back_squat",
    muscleCode: "quads",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "barbell_back_squat",
    muscleCode: "glutes",
    contributionWeight: 0.7,
    isPrimary: false,
  },
  {
    exerciseCode: "barbell_back_squat",
    muscleCode: "core",
    contributionWeight: 0.3,
    isPrimary: false,
  },
  {
    exerciseCode: "barbell_front_squat",
    muscleCode: "quads",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "barbell_front_squat",
    muscleCode: "core",
    contributionWeight: 0.4,
    isPrimary: false,
  },
  {
    exerciseCode: "barbell_front_squat",
    muscleCode: "glutes",
    contributionWeight: 0.45,
    isPrimary: false,
  },
  {
    exerciseCode: "leg_press_machine",
    muscleCode: "quads",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "leg_press_machine",
    muscleCode: "glutes",
    contributionWeight: 0.55,
    isPrimary: false,
  },
  {
    exerciseCode: "romanian_deadlift_barbell",
    muscleCode: "hamstrings",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "romanian_deadlift_barbell",
    muscleCode: "glutes",
    contributionWeight: 0.8,
    isPrimary: false,
  },
  {
    exerciseCode: "deadlift_barbell",
    muscleCode: "glutes",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "deadlift_barbell",
    muscleCode: "hamstrings",
    contributionWeight: 0.8,
    isPrimary: false,
  },
  {
    exerciseCode: "deadlift_barbell",
    muscleCode: "upper_back",
    contributionWeight: 0.6,
    isPrimary: false,
  },
  {
    exerciseCode: "deadlift_barbell",
    muscleCode: "core",
    contributionWeight: 0.35,
    isPrimary: false,
  },
  {
    exerciseCode: "leg_curl_machine",
    muscleCode: "hamstrings",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "leg_extension_machine",
    muscleCode: "quads",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "hip_thrust_barbell",
    muscleCode: "glutes",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "hip_thrust_barbell",
    muscleCode: "hamstrings",
    contributionWeight: 0.35,
    isPrimary: false,
  },
  {
    exerciseCode: "standing_calf_raise_machine",
    muscleCode: "calves",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "barbell_curl",
    muscleCode: "biceps",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "triceps_pushdown_cable",
    muscleCode: "triceps",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "cable_crunch",
    muscleCode: "core",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "cable_fly",
    muscleCode: "chest",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "chest_fly_machine",
    muscleCode: "chest",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "machine_chest_press",
    muscleCode: "chest",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "machine_chest_press",
    muscleCode: "triceps",
    contributionWeight: 0.45,
    isPrimary: false,
  },
  {
    exerciseCode: "push_up_bodyweight",
    muscleCode: "chest",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "push_up_bodyweight",
    muscleCode: "triceps",
    contributionWeight: 0.45,
    isPrimary: false,
  },
  {
    exerciseCode: "dip_bodyweight",
    muscleCode: "triceps",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "dip_bodyweight",
    muscleCode: "chest",
    contributionWeight: 0.65,
    isPrimary: false,
  },
  {
    exerciseCode: "seated_dumbbell_shoulder_press",
    muscleCode: "front_delts",
    contributionWeight: 0.45,
    isPrimary: true,
  },
  {
    exerciseCode: "seated_dumbbell_shoulder_press",
    muscleCode: "side_delts",
    contributionWeight: 0.3,
    isPrimary: false,
  },
  {
    exerciseCode: "seated_dumbbell_shoulder_press",
    muscleCode: "triceps",
    contributionWeight: 0.25,
    isPrimary: false,
  },
  {
    exerciseCode: "machine_shoulder_press",
    muscleCode: "front_delts",
    contributionWeight: 0.5,
    isPrimary: true,
  },
  {
    exerciseCode: "machine_shoulder_press",
    muscleCode: "side_delts",
    contributionWeight: 0.3,
    isPrimary: false,
  },
  {
    exerciseCode: "machine_shoulder_press",
    muscleCode: "triceps",
    contributionWeight: 0.2,
    isPrimary: false,
  },
  {
    exerciseCode: "front_raise_dumbbell",
    muscleCode: "front_delts",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "chin_up_bodyweight",
    muscleCode: "lats",
    contributionWeight: 0.5,
    isPrimary: true,
  },
  {
    exerciseCode: "chin_up_bodyweight",
    muscleCode: "biceps",
    contributionWeight: 0.3,
    isPrimary: false,
  },
  {
    exerciseCode: "chin_up_bodyweight",
    muscleCode: "upper_back",
    contributionWeight: 0.2,
    isPrimary: false,
  },
  {
    exerciseCode: "straight_arm_pulldown_cable",
    muscleCode: "lats",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "dumbbell_row",
    muscleCode: "upper_back",
    contributionWeight: 0.4,
    isPrimary: true,
  },
  {
    exerciseCode: "dumbbell_row",
    muscleCode: "lats",
    contributionWeight: 0.35,
    isPrimary: false,
  },
  {
    exerciseCode: "dumbbell_row",
    muscleCode: "biceps",
    contributionWeight: 0.15,
    isPrimary: false,
  },
  {
    exerciseCode: "dumbbell_row",
    muscleCode: "rear_delts",
    contributionWeight: 0.1,
    isPrimary: false,
  },
  {
    exerciseCode: "t_bar_row",
    muscleCode: "upper_back",
    contributionWeight: 0.45,
    isPrimary: true,
  },
  {
    exerciseCode: "t_bar_row",
    muscleCode: "lats",
    contributionWeight: 0.35,
    isPrimary: false,
  },
  {
    exerciseCode: "t_bar_row",
    muscleCode: "biceps",
    contributionWeight: 0.2,
    isPrimary: false,
  },
  {
    exerciseCode: "bulgarian_split_squat",
    muscleCode: "quads",
    contributionWeight: 0.5,
    isPrimary: true,
  },
  {
    exerciseCode: "bulgarian_split_squat",
    muscleCode: "glutes",
    contributionWeight: 0.35,
    isPrimary: false,
  },
  {
    exerciseCode: "bulgarian_split_squat",
    muscleCode: "hamstrings",
    contributionWeight: 0.15,
    isPrimary: false,
  },
  {
    exerciseCode: "dumbbell_curl",
    muscleCode: "biceps",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "hammer_curl_dumbbell",
    muscleCode: "biceps",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "plank_bodyweight",
    muscleCode: "core",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "hanging_leg_raise",
    muscleCode: "core",
    contributionWeight: 1.0,
    isPrimary: true,
  },
  {
    exerciseCode: "russian_twist",
    muscleCode: "core",
    contributionWeight: 1.0,
    isPrimary: true,
  },
] as const;
