export const exerciseSeeds = [
  {
    code: "bench_press_barbell",
    nameEn: "Barbell Bench Press",
    nameZh: "\u6760\u94c3\u5367\u63a8",
    movementPattern: "horizontal_push",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "incline_bench_press_barbell",
    nameEn: "Incline Barbell Bench Press",
    nameZh: "\u4e0a\u659c\u6760\u94c3\u5367\u63a8",
    movementPattern: "horizontal_push",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "bench_press_dumbbell",
    nameEn: "Dumbbell Bench Press",
    nameZh: "\u54d1\u94c3\u5367\u63a8",
    movementPattern: "horizontal_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "incline_bench_press_dumbbell",
    nameEn: "Incline Dumbbell Bench Press",
    nameZh: "\u4e0a\u659c\u54d1\u94c3\u5367\u63a8",
    movementPattern: "horizontal_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "machine_chest_press",
    nameEn: "Machine Chest Press",
    nameZh: "\u5668\u68b0\u63a8\u80f8",
    movementPattern: "horizontal_push",
    equipment: "machine",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "cable_fly",
    nameEn: "Cable Fly",
    nameZh: "\u7ef3\u7d22\u5939\u80f8",
    movementPattern: "horizontal_push",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "chest_fly_machine",
    nameEn: "Machine Chest Fly",
    nameZh: "\u8774\u8776\u673a\u5939\u80f8",
    movementPattern: "horizontal_push",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "push_up_bodyweight",
    nameEn: "Push-Up",
    nameZh: "\u4fef\u5367\u6491",
    movementPattern: "horizontal_push",
    equipment: "bodyweight",
    isCompound: true,
    defaultRestSeconds: 90,
  },
  {
    code: "dip_bodyweight",
    nameEn: "Parallel Bar Dip",
    nameZh: "\u53cc\u6760\u81c2\u5c48\u4f38",
    movementPattern: "vertical_push",
    equipment: "bodyweight",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "shoulder_press_barbell",
    nameEn: "Barbell Shoulder Press",
    nameZh: "\u6760\u94c3\u63a8\u80a9",
    movementPattern: "vertical_push",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "shoulder_press_dumbbell",
    nameEn: "Dumbbell Shoulder Press",
    nameZh: "\u54d1\u94c3\u63a8\u80a9",
    movementPattern: "vertical_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "seated_dumbbell_shoulder_press",
    nameEn: "Seated Dumbbell Shoulder Press",
    nameZh: "\u5750\u59ff\u54d1\u94c3\u63a8\u80a9",
    movementPattern: "vertical_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "machine_shoulder_press",
    nameEn: "Machine Shoulder Press",
    nameZh: "\u5668\u68b0\u63a8\u80a9",
    movementPattern: "vertical_push",
    equipment: "machine",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "lateral_raise_dumbbell",
    nameEn: "Dumbbell Lateral Raise",
    nameZh: "\u54d1\u94c3\u4fa7\u5e73\u4e3e",
    movementPattern: "shoulder_abduction",
    equipment: "dumbbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "front_raise_dumbbell",
    nameEn: "Dumbbell Front Raise",
    nameZh: "\u54d1\u94c3\u524d\u5e73\u4e3e",
    movementPattern: "shoulder_flexion",
    equipment: "dumbbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "rear_delt_fly_machine",
    nameEn: "Machine Rear Delt Fly",
    nameZh: "\u5668\u68b0\u53cd\u5411\u98de\u9e1f",
    movementPattern: "horizontal_pull",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "pull_up_bodyweight",
    nameEn: "Pull-Up",
    nameZh: "\u5f15\u4f53\u5411\u4e0a",
    movementPattern: "vertical_pull",
    equipment: "bodyweight",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "chin_up_bodyweight",
    nameEn: "Chin-Up",
    nameZh: "\u53cd\u624b\u5f15\u4f53",
    movementPattern: "vertical_pull",
    equipment: "bodyweight",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "lat_pulldown_cable",
    nameEn: "Lat Pulldown",
    nameZh: "\u9ad8\u4f4d\u4e0b\u62c9",
    movementPattern: "vertical_pull",
    equipment: "cable",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "straight_arm_pulldown_cable",
    nameEn: "Cable Straight-Arm Pulldown",
    nameZh: "\u7ef3\u7d22\u76f4\u81c2\u4e0b\u538b",
    movementPattern: "vertical_pull",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "barbell_row",
    nameEn: "Barbell Row",
    nameZh: "\u6760\u94c3\u5212\u8239",
    movementPattern: "horizontal_pull",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "dumbbell_row",
    nameEn: "Dumbbell Row",
    nameZh: "\u54d1\u94c3\u5212\u8239",
    movementPattern: "horizontal_pull",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "t_bar_row",
    nameEn: "T-Bar Row",
    nameZh: "T\u6760\u5212\u8239",
    movementPattern: "horizontal_pull",
    equipment: "machine",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "seated_cable_row",
    nameEn: "Seated Cable Row",
    nameZh: "\u5750\u59ff\u5212\u8239",
    movementPattern: "horizontal_pull",
    equipment: "cable",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "face_pull_cable",
    nameEn: "Cable Face Pull",
    nameZh: "\u7ef3\u7d22\u9762\u62c9",
    movementPattern: "horizontal_pull",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "barbell_back_squat",
    nameEn: "Barbell Back Squat",
    nameZh: "\u6760\u94c3\u6df1\u8e72",
    movementPattern: "squat",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 180,
  },
  {
    code: "barbell_front_squat",
    nameEn: "Barbell Front Squat",
    nameZh: "\u6760\u94c3\u524d\u8e72",
    movementPattern: "squat",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 180,
  },
  {
    code: "leg_press_machine",
    nameEn: "Leg Press",
    nameZh: "\u817f\u4e3e",
    movementPattern: "squat",
    equipment: "machine",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "bulgarian_split_squat",
    nameEn: "Bulgarian Split Squat",
    nameZh: "\u4fdd\u52a0\u5229\u4e9a\u5206\u817f\u8e72",
    movementPattern: "squat",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "romanian_deadlift_barbell",
    nameEn: "Barbell Romanian Deadlift",
    nameZh: "\u6760\u94c3\u7f57\u9a6c\u5c3c\u4e9a\u786c\u62c9",
    movementPattern: "hinge",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "deadlift_barbell",
    nameEn: "Barbell Deadlift",
    nameZh: "\u6760\u94c3\u786c\u62c9",
    movementPattern: "hinge",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 180,
  },
  {
    code: "leg_curl_machine",
    nameEn: "Machine Leg Curl",
    nameZh: "\u5668\u68b0\u817f\u5f2f\u4e3e",
    movementPattern: "knee_flexion",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "leg_extension_machine",
    nameEn: "Machine Leg Extension",
    nameZh: "\u5668\u68b0\u817f\u5c48\u4f38",
    movementPattern: "knee_extension",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "hip_thrust_barbell",
    nameEn: "Barbell Hip Thrust",
    nameZh: "\u6760\u94c3\u81c0\u63a8",
    movementPattern: "hinge",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "standing_calf_raise_machine",
    nameEn: "Standing Calf Raise",
    nameZh: "\u7ad9\u59ff\u63d0\u8e35",
    movementPattern: "plantar_flexion",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "barbell_curl",
    nameEn: "Barbell Curl",
    nameZh: "\u6760\u94c3\u5f2f\u4e3e",
    movementPattern: "elbow_flexion",
    equipment: "barbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "dumbbell_curl",
    nameEn: "Dumbbell Curl",
    nameZh: "\u54d1\u94c3\u5f2f\u4e3e",
    movementPattern: "elbow_flexion",
    equipment: "dumbbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "hammer_curl_dumbbell",
    nameEn: "Dumbbell Hammer Curl",
    nameZh: "\u9524\u5f0f\u5f2f\u4e3e",
    movementPattern: "elbow_flexion",
    equipment: "dumbbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "triceps_pushdown_cable",
    nameEn: "Cable Triceps Pushdown",
    nameZh: "\u7ef3\u7d22\u4e0b\u538b",
    movementPattern: "elbow_extension",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "cable_crunch",
    nameEn: "Cable Crunch",
    nameZh: "\u7ef3\u7d22\u5377\u8179",
    movementPattern: "spinal_flexion",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 60,
  },
  {
    code: "plank_bodyweight",
    nameEn: "Plank",
    nameZh: "\u5e73\u677f\u652f\u6491",
    movementPattern: "anti_extension",
    equipment: "bodyweight",
    isCompound: false,
    defaultRestSeconds: 60,
  },
  {
    code: "hanging_leg_raise",
    nameEn: "Hanging Leg Raise",
    nameZh: "\u60ac\u5782\u4e3e\u817f",
    movementPattern: "hip_flexion",
    equipment: "bodyweight",
    isCompound: false,
    defaultRestSeconds: 60,
  },
  {
    code: "russian_twist",
    nameEn: "Russian Twist",
    nameZh: "\u4fc4\u7f57\u65af\u8f6c\u4f53",
    movementPattern: "rotation",
    equipment: "bodyweight",
    isCompound: false,
    defaultRestSeconds: 60,
  },
] as const;
