const baseExerciseSeeds = [
  {
    code: "bench_press_barbell",
    nameEn: "Barbell Bench Press",
    nameZh: "\u6760\u94c3\u5367\u63a8",
    movementPattern: "horizontal_push",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "incline_bench_press_barbell",
    nameEn: "Incline Barbell Bench Press",
    nameZh: "\u4e0a\u659c\u6760\u94c3\u5367\u63a8",
    movementPattern: "horizontal_push",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "bench_press_dumbbell",
    nameEn: "Dumbbell Bench Press",
    nameZh: "\u54d1\u94c3\u5367\u63a8",
    movementPattern: "horizontal_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "incline_bench_press_dumbbell",
    nameEn: "Incline Dumbbell Bench Press",
    nameZh: "\u4e0a\u659c\u54d1\u94c3\u5367\u63a8",
    movementPattern: "horizontal_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "machine_chest_press",
    nameEn: "Machine Chest Press",
    nameZh: "\u5668\u68b0\u63a8\u80f8",
    movementPattern: "horizontal_push",
    equipment: "machine",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "cable_fly",
    nameEn: "Cable Fly",
    nameZh: "\u7ef3\u7d22\u5939\u80f8",
    movementPattern: "horizontal_push",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "chest_fly_machine",
    nameEn: "Machine Chest Fly",
    nameZh: "\u8774\u8776\u673a\u5939\u80f8",
    movementPattern: "horizontal_push",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "push_up_bodyweight",
    nameEn: "Push-Up",
    nameZh: "\u4fef\u5367\u6491",
    movementPattern: "horizontal_push",
    equipment: "bodyweight",
    isCompound: true,
    defaultRestSeconds: 90,
  },
  {
    code: "dip_bodyweight",
    nameEn: "Parallel Bar Dip",
    nameZh: "\u53cc\u6760\u81c2\u5c48\u4f38",
    movementPattern: "vertical_push",
    equipment: "bodyweight",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "shoulder_press_barbell",
    nameEn: "Barbell Shoulder Press",
    nameZh: "\u6760\u94c3\u63a8\u80a9",
    movementPattern: "vertical_push",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "shoulder_press_dumbbell",
    nameEn: "Dumbbell Shoulder Press",
    nameZh: "\u54d1\u94c3\u63a8\u80a9",
    movementPattern: "vertical_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "seated_dumbbell_shoulder_press",
    nameEn: "Seated Dumbbell Shoulder Press",
    nameZh: "\u5750\u59ff\u54d1\u94c3\u63a8\u80a9",
    movementPattern: "vertical_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "machine_shoulder_press",
    nameEn: "Machine Shoulder Press",
    nameZh: "\u5668\u68b0\u63a8\u80a9",
    movementPattern: "vertical_push",
    equipment: "machine",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "lateral_raise_dumbbell",
    nameEn: "Dumbbell Lateral Raise",
    nameZh: "\u54d1\u94c3\u4fa7\u5e73\u4e3e",
    movementPattern: "shoulder_abduction",
    equipment: "dumbbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "front_raise_dumbbell",
    nameEn: "Dumbbell Front Raise",
    nameZh: "\u54d1\u94c3\u524d\u5e73\u4e3e",
    movementPattern: "shoulder_flexion",
    equipment: "dumbbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "rear_delt_fly_machine",
    nameEn: "Machine Rear Delt Fly",
    nameZh: "\u5668\u68b0\u53cd\u5411\u98de\u9e1f",
    movementPattern: "horizontal_pull",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "pull_up_bodyweight",
    nameEn: "Pull-Up",
    nameZh: "\u5f15\u4f53\u5411\u4e0a",
    movementPattern: "vertical_pull",
    equipment: "bodyweight",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "chin_up_bodyweight",
    nameEn: "Chin-Up",
    nameZh: "\u53cd\u624b\u5f15\u4f53",
    movementPattern: "vertical_pull",
    equipment: "bodyweight",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "lat_pulldown_cable",
    nameEn: "Lat Pulldown",
    nameZh: "\u9ad8\u4f4d\u4e0b\u62c9",
    movementPattern: "vertical_pull",
    equipment: "cable",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "straight_arm_pulldown_cable",
    nameEn: "Cable Straight-Arm Pulldown",
    nameZh: "\u7ef3\u7d22\u76f4\u81c2\u4e0b\u538b",
    movementPattern: "vertical_pull",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "barbell_row",
    nameEn: "Barbell Row",
    nameZh: "\u6760\u94c3\u5212\u8239",
    movementPattern: "horizontal_pull",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "dumbbell_row",
    nameEn: "Dumbbell Row",
    nameZh: "\u54d1\u94c3\u5212\u8239",
    movementPattern: "horizontal_pull",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "t_bar_row",
    nameEn: "T-Bar Row",
    nameZh: "T\u6760\u5212\u8239",
    movementPattern: "horizontal_pull",
    equipment: "machine",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "seated_cable_row",
    nameEn: "Seated Cable Row",
    nameZh: "\u5750\u59ff\u5212\u8239",
    movementPattern: "horizontal_pull",
    equipment: "cable",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "face_pull_cable",
    nameEn: "Cable Face Pull",
    nameZh: "\u7ef3\u7d22\u9762\u62c9",
    movementPattern: "horizontal_pull",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "barbell_back_squat",
    nameEn: "Barbell Back Squat",
    nameZh: "\u6760\u94c3\u6df1\u8e72",
    movementPattern: "squat",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 180,
  },
  {
    code: "barbell_front_squat",
    nameEn: "Barbell Front Squat",
    nameZh: "\u6760\u94c3\u524d\u8e72",
    movementPattern: "squat",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 180,
  },
  {
    code: "leg_press_machine",
    nameEn: "Leg Press",
    nameZh: "\u817f\u4e3e",
    movementPattern: "squat",
    equipment: "machine",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "bulgarian_split_squat",
    nameEn: "Bulgarian Split Squat",
    nameZh: "\u4fdd\u52a0\u5229\u4e9a\u5206\u817f\u8e72",
    movementPattern: "squat",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "romanian_deadlift_barbell",
    nameEn: "Barbell Romanian Deadlift",
    nameZh: "\u6760\u94c3\u7f57\u9a6c\u5c3c\u4e9a\u786c\u62c9",
    movementPattern: "hinge",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "deadlift_barbell",
    nameEn: "Barbell Deadlift",
    nameZh: "\u6760\u94c3\u786c\u62c9",
    movementPattern: "hinge",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 180,
  },
  {
    code: "leg_curl_machine",
    nameEn: "Machine Leg Curl",
    nameZh: "\u5668\u68b0\u817f\u5f2f\u4e3e",
    movementPattern: "knee_flexion",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "leg_extension_machine",
    nameEn: "Machine Leg Extension",
    nameZh: "\u5668\u68b0\u817f\u5c48\u4f38",
    movementPattern: "knee_extension",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "hip_thrust_barbell",
    nameEn: "Barbell Hip Thrust",
    nameZh: "\u6760\u94c3\u81c0\u63a8",
    movementPattern: "hinge",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "standing_calf_raise_machine",
    nameEn: "Standing Calf Raise",
    nameZh: "\u7ad9\u59ff\u63d0\u8e35",
    movementPattern: "plantar_flexion",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "barbell_curl",
    nameEn: "Barbell Curl",
    nameZh: "\u6760\u94c3\u5f2f\u4e3e",
    movementPattern: "elbow_flexion",
    equipment: "barbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "dumbbell_curl",
    nameEn: "Dumbbell Curl",
    nameZh: "\u54d1\u94c3\u5f2f\u4e3e",
    movementPattern: "elbow_flexion",
    equipment: "dumbbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "hammer_curl_dumbbell",
    nameEn: "Dumbbell Hammer Curl",
    nameZh: "\u9524\u5f0f\u5f2f\u4e3e",
    movementPattern: "elbow_flexion",
    equipment: "dumbbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "triceps_pushdown_cable",
    nameEn: "Cable Triceps Pushdown",
    nameZh: "\u7ef3\u7d22\u4e0b\u538b",
    movementPattern: "elbow_extension",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "cable_crunch",
    nameEn: "Cable Crunch",
    nameZh: "\u7ef3\u7d22\u5377\u8179",
    movementPattern: "spinal_flexion",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 60,
  },
  {
    code: "plank_bodyweight",
    nameEn: "Plank",
    nameZh: "\u5e73\u677f\u652f\u6491",
    movementPattern: "anti_extension",
    equipment: "bodyweight",
    isCompound: false,
    defaultRestSeconds: 60,
  },
  {
    code: "hanging_leg_raise",
    nameEn: "Hanging Leg Raise",
    nameZh: "\u60ac\u5782\u4e3e\u817f",
    movementPattern: "hip_flexion",
    equipment: "bodyweight",
    isCompound: false,
    defaultRestSeconds: 60,
  },
  {
    code: "russian_twist",
    nameEn: "Russian Twist",
    nameZh: "\u4fc4\u7f57\u65af\u8f6c\u4f53",
    movementPattern: "rotation",
    equipment: "bodyweight",
    isCompound: false,
    defaultRestSeconds: 60,
  },
] as const;

type BaseExerciseSeed = (typeof baseExerciseSeeds)[number];

const movementDetailMap: Record<
  string,
  { cues: string[]; mistakes: string[] }
> = {
  anti_extension: {
    cues: ["收紧腹部和臀部，让身体从头到脚保持一条直线。", "用稳定呼吸维持姿势，不要憋气硬撑。"],
    mistakes: ["塌腰或撅臀会降低核心训练效果。", "肩膀耸起、脖子紧张会让动作变形。"],
  },
  elbow_extension: {
    cues: ["上臂保持稳定，主要用肘关节完成伸展。", "下压到底时短暂停顿，感受肱三头肌收缩。"],
    mistakes: ["身体前后晃动借力会削弱目标肌群刺激。", "手腕过度弯折容易造成不适。"],
  },
  elbow_flexion: {
    cues: ["保持上臂贴近身体，控制哑铃或杠铃上升。", "下降阶段放慢速度，保持肌肉张力。"],
    mistakes: ["甩动身体借力会让手臂刺激不足。", "肘部明显前移会改变动作轨迹。"],
  },
  gait: {
    cues: ["保持身体直立，步幅稳定，脚步轻落地。", "根据训练目标控制速度和呼吸节奏。"],
    mistakes: ["疲劳后含胸低头会影响呼吸和姿态。", "速度过快导致动作失控会增加受伤风险。"],
  },
  hip_flexion: {
    cues: ["先收紧核心，再抬腿，避免身体大幅摆动。", "抬起时呼气，下降时保持控制。"],
    mistakes: ["利用惯性甩腿会减少核心参与。", "下放过快容易让腰部代偿。"],
  },
  horizontal_pull: {
    cues: ["先稳定躯干，再把肘部向身体后方拉。", "顶峰位置夹紧背部，下降时保持控制。"],
    mistakes: ["耸肩或用手臂硬拉会削弱背部发力。", "身体晃动过大会让重量失去参考价值。"],
  },
  horizontal_push: {
    cues: ["肩胛保持稳定，推起时让手臂沿自然轨迹发力。", "下降阶段控制速度，底部不要放松。"],
    mistakes: ["肩膀前顶会增加肩部压力。", "弹起重量或半程动作会影响训练质量。"],
  },
  knee_dominant: {
    cues: ["膝盖跟随脚尖方向移动，保持脚掌稳定。", "下降和起身都要控制节奏，避免失去平衡。"],
    mistakes: ["膝盖内扣会增加关节压力。", "为了重量牺牲动作深度会降低训练效果。"],
  },
  lunge: {
    cues: ["前脚踩稳，身体保持直立，核心收紧。", "下降时控制膝盖方向，起身时用前腿发力。"],
    mistakes: ["步距过窄会让身体左右晃动。", "后脚蹬地过多会减少前腿刺激。"],
  },
  plantar_flexion: {
    cues: ["脚掌稳定踩实，抬起脚跟时在顶端短暂停顿。", "下降到可控范围，感受小腿被拉长。"],
    mistakes: ["快速弹动会减少有效刺激。", "脚踝向内或向外翻会影响发力。"],
  },
  rotation: {
    cues: ["核心先收紧，再控制躯干旋转。", "动作幅度以稳定为先，不追求过快速度。"],
    mistakes: ["只用手臂摆动会削弱核心参与。", "腰部塌陷或后仰会增加不适风险。"],
  },
  shoulder_abduction: {
    cues: ["手肘微弯，从身体两侧平稳抬起。", "抬到肩部附近即可，下降时保持控制。"],
    mistakes: ["耸肩借力会让斜方肌过度参与。", "重量过大导致甩动会影响肩部刺激。"],
  },
  shoulder_flexion: {
    cues: ["核心收紧，手臂向前平稳抬起。", "控制下放速度，保持肩部张力。"],
    mistakes: ["后仰借力会让动作失去控制。", "抬得过高或耸肩会增加肩部压力。"],
  },
  spinal_flexion: {
    cues: ["先收紧腹部，再让胸椎向骨盆方向卷起。", "回到起始位置时保持控制，不要完全放松。"],
    mistakes: ["只用手臂拉绳会减少腹部参与。", "腰部过度弯折可能造成不适。"],
  },
  vertical_pull: {
    cues: ["先下沉肩胛，再把肘部向下拉。", "顶端保持身体稳定，底部感受背部收缩。"],
    mistakes: ["用身体后仰甩动借力会降低背部刺激。", "只拉到半程会让动作效果打折。"],
  },
  vertical_push: {
    cues: ["核心收紧，推起时让手肘稳定向上伸展。", "下降到可控深度，保持肩部稳定。"],
    mistakes: ["腰部过度后仰会增加下背压力。", "推起时耸肩会让肩颈过度紧张。"],
  },
};

const equipmentNotes: Record<string, string> = {
  barbell: "使用杠铃时先确认握距和杠铃路径稳定，重量增加要循序渐进。",
  bodyweight: "自重动作可以通过节奏、停顿或辅助带调节难度。",
  cable: "使用绳索时先调好滑轮高度，保持拉力方向和动作轨迹一致。",
  dumbbell: "使用哑铃时左右两侧都要保持稳定，优先选择能控制全程的重量。",
  kettlebell: "使用壶铃时注意握持稳定，摆动类动作先保证髋部发力和节奏。",
  machine: "使用器械时先调好座椅和把手位置，让关节对齐器械轴线。",
  plate: "使用杠铃片时握持要稳，避免手腕过度弯折。",
  resistance_band: "使用弹力带时确认固定点牢靠，并控制回弹速度。",
  sled: "使用雪橇时保持躯干稳定，先用可控负重建立节奏。",
};

const fallbackDetail = {
  cues: ["先确认动作姿势稳定，再逐步增加训练重量。", "全程保持可控节奏，优先完成标准动作。"],
  mistakes: ["为了追求重量牺牲动作质量会增加风险。", "动作过快或幅度不足会影响训练效果。"],
};

export const exerciseSeeds = baseExerciseSeeds.map((seed) => {
  const movementDetail =
    (seed.movementPattern ? movementDetailMap[seed.movementPattern] : undefined) ??
    fallbackDetail;
  const equipmentNote =
    (seed.equipment ? equipmentNotes[seed.equipment] : undefined) ??
    "请根据动作需要选择合适器械，并确认训练环境安全。";

  return {
    ...seed,
    commonMistakesZh: movementDetail.mistakes,
    equipmentNotesZh: equipmentNote,
    techniqueCuesZh: movementDetail.cues,
  };
}) satisfies Array<
  BaseExerciseSeed & {
    commonMistakesZh: string[];
    equipmentNotesZh: string;
    techniqueCuesZh: string[];
  }
>;
