export const exerciseSeeds = [
  {
    code: "bench_press_barbell",
    nameEn: "Barbell Bench Press",
    nameZh: "杠铃卧推",
    movementPattern: "horizontal_push",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "incline_bench_press_barbell",
    nameEn: "Incline Barbell Bench Press",
    nameZh: "上斜杠铃卧推",
    movementPattern: "horizontal_push",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "bench_press_dumbbell",
    nameEn: "Dumbbell Bench Press",
    nameZh: "哑铃卧推",
    movementPattern: "horizontal_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "incline_bench_press_dumbbell",
    nameEn: "Incline Dumbbell Bench Press",
    nameZh: "上斜哑铃卧推",
    movementPattern: "horizontal_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "chest_fly_machine",
    nameEn: "Machine Chest Fly",
    nameZh: "器械夹胸",
    movementPattern: "horizontal_push",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "shoulder_press_barbell",
    nameEn: "Barbell Shoulder Press",
    nameZh: "杠铃推举",
    movementPattern: "vertical_push",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "shoulder_press_dumbbell",
    nameEn: "Dumbbell Shoulder Press",
    nameZh: "哑铃推举",
    movementPattern: "vertical_push",
    equipment: "dumbbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "lateral_raise_dumbbell",
    nameEn: "Dumbbell Lateral Raise",
    nameZh: "哑铃侧平举",
    movementPattern: "shoulder_abduction",
    equipment: "dumbbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "rear_delt_fly_machine",
    nameEn: "Machine Rear Delt Fly",
    nameZh: "器械反向飞鸟",
    movementPattern: "horizontal_pull",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "pull_up_bodyweight",
    nameEn: "Pull-Up",
    nameZh: "引体向上",
    movementPattern: "vertical_pull",
    equipment: "bodyweight",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "lat_pulldown_cable",
    nameEn: "Lat Pulldown",
    nameZh: "高位下拉",
    movementPattern: "vertical_pull",
    equipment: "cable",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "barbell_row",
    nameEn: "Barbell Row",
    nameZh: "杠铃划船",
    movementPattern: "horizontal_pull",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "seated_cable_row",
    nameEn: "Seated Cable Row",
    nameZh: "坐姿划船",
    movementPattern: "horizontal_pull",
    equipment: "cable",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "face_pull_cable",
    nameEn: "Cable Face Pull",
    nameZh: "绳索面拉",
    movementPattern: "horizontal_pull",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "barbell_back_squat",
    nameEn: "Barbell Back Squat",
    nameZh: "杠铃深蹲",
    movementPattern: "squat",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 180,
  },
  {
    code: "barbell_front_squat",
    nameEn: "Barbell Front Squat",
    nameZh: "杠铃前蹲",
    movementPattern: "squat",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 180,
  },
  {
    code: "leg_press_machine",
    nameEn: "Leg Press",
    nameZh: "腿举",
    movementPattern: "squat",
    equipment: "machine",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "romanian_deadlift_barbell",
    nameEn: "Barbell Romanian Deadlift",
    nameZh: "杠铃罗马尼亚硬拉",
    movementPattern: "hinge",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 150,
  },
  {
    code: "deadlift_barbell",
    nameEn: "Barbell Deadlift",
    nameZh: "杠铃硬拉",
    movementPattern: "hinge",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 180,
  },
  {
    code: "leg_curl_machine",
    nameEn: "Machine Leg Curl",
    nameZh: "器械腿弯举",
    movementPattern: "knee_flexion",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "leg_extension_machine",
    nameEn: "Machine Leg Extension",
    nameZh: "器械腿屈伸",
    movementPattern: "knee_extension",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 90,
  },
  {
    code: "hip_thrust_barbell",
    nameEn: "Barbell Hip Thrust",
    nameZh: "杠铃臀推",
    movementPattern: "hinge",
    equipment: "barbell",
    isCompound: true,
    defaultRestSeconds: 120,
  },
  {
    code: "standing_calf_raise_machine",
    nameEn: "Standing Calf Raise",
    nameZh: "站姿提踵",
    movementPattern: "plantar_flexion",
    equipment: "machine",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "barbell_curl",
    nameEn: "Barbell Curl",
    nameZh: "杠铃弯举",
    movementPattern: "elbow_flexion",
    equipment: "barbell",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "triceps_pushdown_cable",
    nameEn: "Cable Triceps Pushdown",
    nameZh: "绳索下压",
    movementPattern: "elbow_extension",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 75,
  },
  {
    code: "cable_crunch",
    nameEn: "Cable Crunch",
    nameZh: "绳索卷腹",
    movementPattern: "spinal_flexion",
    equipment: "cable",
    isCompound: false,
    defaultRestSeconds: 60,
  },
] as const;
