export const muscleGroupSeeds = [
  { code: "chest", nameEn: "Chest", nameZh: "胸", parentCode: null, recoveryHours: 48 },
  { code: "upper_chest", nameEn: "Upper Chest", nameZh: "上胸", parentCode: "chest", recoveryHours: 48 },
  { code: "back", nameEn: "Back", nameZh: "背", parentCode: null, recoveryHours: 48 },
  { code: "lats", nameEn: "Lats", nameZh: "背阔肌", parentCode: "back", recoveryHours: 48 },
  { code: "upper_back", nameEn: "Upper Back", nameZh: "上背", parentCode: "back", recoveryHours: 48 },
  { code: "legs", nameEn: "Legs", nameZh: "腿", parentCode: null, recoveryHours: 72 },
  { code: "quads", nameEn: "Quads", nameZh: "股四头", parentCode: "legs", recoveryHours: 72 },
  { code: "hamstrings", nameEn: "Hamstrings", nameZh: "腘绳肌", parentCode: "legs", recoveryHours: 72 },
  { code: "glutes", nameEn: "Glutes", nameZh: "臀", parentCode: "legs", recoveryHours: 72 },
  { code: "calves", nameEn: "Calves", nameZh: "小腿", parentCode: "legs", recoveryHours: 48 },
  { code: "shoulders", nameEn: "Shoulders", nameZh: "肩", parentCode: null, recoveryHours: 48 },
  { code: "front_delts", nameEn: "Front Delts", nameZh: "三角肌前束", parentCode: "shoulders", recoveryHours: 48 },
  { code: "side_delts", nameEn: "Side Delts", nameZh: "三角肌中束", parentCode: "shoulders", recoveryHours: 48 },
  { code: "rear_delts", nameEn: "Rear Delts", nameZh: "三角肌后束", parentCode: "shoulders", recoveryHours: 48 },
  { code: "biceps", nameEn: "Biceps", nameZh: "肱二头", parentCode: null, recoveryHours: 24 },
  { code: "triceps", nameEn: "Triceps", nameZh: "肱三头", parentCode: null, recoveryHours: 24 },
  { code: "core", nameEn: "Core", nameZh: "核心", parentCode: null, recoveryHours: 24 },
] as const;
