import type { SemanticTone } from "../../theme/tokens";
import { requestJson } from "../../services/http-client";
import type {
  AssistantMode,
  AssistantPromptSuggestion,
} from "./assistant-types";

export type AssistantInsightType =
  | "next_training_focus"
  | "training_imbalance"
  | "recovery_check"
  | "exercise_progress"
  | "evidence_explain";

export interface AssistantInsightsRange {
  start_date: string;
  end_date: string;
}

export interface AssistantInsightsOverview {
  workout_count: number;
  set_count: number;
  total_volume: number;
  top_muscle_group_name: string | null;
  top_exercise_name: string | null;
}

export interface AssistantInsightCard {
  type: AssistantInsightType;
  title: string;
  summary: string;
  tone: SemanticTone;
  hint?: string | undefined;
  evidence_summary?: string | undefined;
  suggested_prompt?: AssistantPromptSuggestion | undefined;
}

export interface AssistantInsightsEvidence {
  workout_count: number;
  set_count: number;
  calculation_sources: string[];
  calculation_rules: string[];
}

export interface AssistantInsightsResponse {
  range: AssistantInsightsRange;
  overview: AssistantInsightsOverview;
  cards: AssistantInsightCard[];
  limitations: string[];
  evidence: AssistantInsightsEvidence;
}

interface AssistantInsightsQuery {
  endDate: string;
  exerciseId?: string | null | undefined;
  startDate: string;
}

/**
 * Loads deterministic assistant insight cards generated by the backend.
 *
 * @param token - In-memory auth token
 * @param query - Date range and optional selected exercise
 * @returns Assistant insight dashboard view-model
 */
export async function getAssistantInsights(
  token: string,
  query: AssistantInsightsQuery,
): Promise<AssistantInsightsResponse> {
  const searchParams = new URLSearchParams({
    end_date: query.endDate,
    start_date: query.startDate,
  });

  if (query.exerciseId) {
    searchParams.set("exercise_id", query.exerciseId);
  }

  return requestJson<AssistantInsightsResponse>(
    `/api/training/assistant-insights?${searchParams.toString()}`,
    {
      token,
    },
  );
}

export function isAssistantMode(value: string): value is AssistantMode {
  return [
    "training_overview",
    "exercise_progress",
    "next_training_focus",
    "muscle_balance",
    "training_imbalance",
    "recovery_check",
    "evidence_explain",
    "unsupported",
  ].includes(value);
}
